bottom_up_tree_node:
  ros__parameters:
    init_delay: 1.5
    robot_approach_subject_distance : 0.25 #TODO: test optimum
    robot_closeness_threshold: 0.4 #TODO: test optimum
    target_reached_threshold: 0.4  #TODO: test optimum
    Dog_look_for_feedback_delay: 2.0

    target_position:
      - 1.2 #X
      - 0.8 #Y
      - 0.0 #Z
      
    LED_indicate_target_seq:
      - "{'fl':{'mode':1, 'color':1},'fr':{'mode':2, 'color':1},'bl':{'mode':2, 'color':1},'br':{'mode':1, 'color':1}}" #pulse ahead white
      - "{'fl':{'mode':4, 'color':0},'fr':{'mode':4, 'color':0},'bl':{'mode':4, 'color':0},'br':{'mode':4, 'color':0}}" #black fix
      - "{'fl':{'mode':4, 'color':7},'fr':{'mode':4, 'color':7},'bl':{'mode':4, 'color':7},'br':{'mode':4, 'color':7}}" # yellow fix
      - "{'fl':{'mode':4, 'color':0},'fr':{'mode':4, 'color':0},'bl':{'mode':4, 'color':0},'br':{'mode':4, 'color':0}}" #black fix
      - "{'fl':{'mode':4, 'color':7},'fr':{'mode':4, 'color':7},'bl':{'mode':4, 'color':7},'br':{'mode':4, 'color':7}}" # yellow fix
      - "{'fl':{'mode':4, 'color':0},'fr':{'mode':4, 'color':0},'bl':{'mode':4, 'color':0},'br':{'mode':4, 'color':0}}" #black fix
      - "{'fl':{'mode':4, 'color':7},'fr':{'mode':4, 'color':7},'bl':{'mode':4, 'color':7},'br':{'mode':4, 'color':7}}" # yellow fix
      - "{'fl':{'mode':4, 'color':0},'fr':{'mode':4, 'color':0},'bl':{'mode':4, 'color':0},'br':{'mode':4, 'color':0}}" #black fix
      - "{'fl':{'mode':1, 'color':1},'fr':{'mode':2, 'color':1},'bl':{'mode':2, 'color':1},'br':{'mode':1, 'color':1}}" #pulse ahead white
      - "{'fl':{'mode':4, 'color':0},'fr':{'mode':4, 'color':0},'bl':{'mode':4, 'color':0},'br':{'mode':4, 'color':0}}" #black fix


    LED_indicate_target_times:
      - 0.5 #white
      - 0.25 #black
      - 0.25 #yellow
      - 0.25 #black
      - 0.25 #yellow
      - 0.25 #black
      - 0.25 #yellow
      - 0.25 #black
      - 0.5 #white 
      - 0.5 #black

    Dog_indicate_target_seq:
       - "{'n_pos':8.5,'gl_pos':3.19,'gr_pos':7.05}" #gripper open, look ahead
       - "{'n_pos':8.5,'gl_pos':7.05,'gr_pos':3.19}" #gripper close, look ahead
       - "{'n_pos':8.5,'gl_pos':3.19,'gr_pos':7.05}" #gripper open, look ahead
       - "{'n_pos':8.5,'gl_pos':7.05,'gr_pos':3.19}" #gripper close, look ahead
       - "{'n_pos':8.5,'gl_pos':3.19,'gr_pos':7.05}" #gripper open, look ahead
       - "{'n_pos':8.5,'gl_pos':7.05,'gr_pos':3.19}" #gripper close, look ahead
       - "{'n_pos':8.5,'gl_pos':5.12,'gr_pos':5.12}" #gripper to default, look ahead
  
    Dog_indicate_target_times:
        - 0.25
        - 0.25
        - 0.25
        - 0.25
        - 0.25
        - 0.25
        - 0.25

    Dog_catch_attention_seq:
       - "{'n_pos':8.90,'gl_pos':5.12,'gr_pos':5.12}" #gripper to default, look up
       - "{'n_pos':8.5,'gl_pos':5.12,'gr_pos':5.12}" #gripper to default, look ahead
       - "{'n_pos':8.90,'gl_pos':5.12,'gr_pos':5.12}" #gripper to default, look up
       - "{'n_pos':8.90,'gl_pos':5.12,'gr_pos':5.12}" #gripper to default, look ahead
       - "{'n_pos':8.80,'gl_pos':5.12,'gr_pos':5.12}" #gripper to default, look up
       - "{'n_pos':8.90,'gl_pos':5.12,'gr_pos':5.12}" #gripper to default, look ahead
    
    Dog_catch_attention_times:
        - 0.25
        - 0.25
        - 0.25
        - 0.25
        - 0.25
        - 0.25
      
    LED_catch_attention_seq:
      - "{'fl':{'mode':1, 'color':1},'fr':{'mode':2, 'color':1},'bl':{'mode':2, 'color':1},'br':{'mode':1, 'color':1}}" #pulse ahead white
      - "{'fl':{'mode':4, 'color':0},'fr':{'mode':4, 'color':0},'bl':{'mode':4, 'color':0},'br':{'mode':4, 'color':0}}" #black fix
      - "{'fl':{'mode':1, 'color':1},'fr':{'mode':2, 'color':1},'bl':{'mode':2, 'color':1},'br':{'mode':1, 'color':1}}" #pulse ahead white
      - "{'fl':{'mode':4, 'color':0},'fr':{'mode':4, 'color':0},'bl':{'mode':4, 'color':0},'br':{'mode':4, 'color':0}}" #black fix
    
    LED_catch_attention_times:
        - 0.5 #white
        - 0.25 #black
        - 0.5 #white
        - 0.25 #black